
# ========== SPI NOR Flash（spi00, P25Q64SH）==========
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y

# SPI 总线 + SPI NOR 驱动
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_DEVICETREE=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
# CONFIG_SPI_NOR_SFDP_RUNTIME is not set

# ========== 外设电源管理 ==========
CONFIG_PM_DEVICE=y
#CONFIG_PM_DEVICE_RUNTIME=y

# ========== Button1/Button2 GPIO wake ==========
CONFIG_GPIO=y

# ========== UART21 Console ==========
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_RTT_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n

# ========== LOG 后端：UART21 ==========
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_PRINTK=y

# ========== 关闭不需要的外设 ==========
CONFIG_I2C=n
CONFIG_ADC=n
CONFIG_PWM=n
CONFIG_HWINFO=n
CONFIG_WATCHDOG=n

# ========== 减少启动开销 ==========
CONFIG_BOOT_BANNER=n


# #开启dfu,会有一个SMP Service
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU_SPEEDUP=y
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="OTA_LBS"
CONFIG_BT_LBS=y
CONFIG_BT_LBS_POLL_BUTTON=y

