SB_CONFIG_BOOTLOADER_MCUBOOT=y
#add by david comment below config for disable compress DFU
#SB_CONFIG_MCUBOOT_COMPRESSED_IMAGE_SUPPORT=y
#SB_CONFIG_MCUBOOT_UPDATEABLE_IMAGES=1
#SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y

#external flash
#SB_CONFIG_PARTITION_MANAGER=y
SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
SB_CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

