# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: Apache-2.0
#
CONFIG_BOOT_MAX_IMG_SECTORS=512

# Enable write buffer for faster writes to RRAM
CONFIG_NRF_RRAM_WRITE_BUFFER_SIZE=32

CONFIG_FLASH=y


CONFIG_BOOT_BOOTSTRAP=n
CONFIG_MAIN_STACK_SIZE=10240

# CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n

# Ensure that the SPI NOR driver is disabled by default
CONFIG_SPI_NOR=n

# TODO: below are not yet supported and need fixing
CONFIG_FPROTECT=n

CONFIG_BOOT_WATCHDOG_FEED=n


CONFIG_PM=n