CONFIG_PM=n

CONFIG_MAIN_STACK_SIZE=10240
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024

#CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n

#CONFIG_BOOT_UPGRADE_ONLY=y
CONFIG_BOOT_BOOTSTRAP=n

### mbedTLS has its own heap
# CONFIG_HEAP_MEM_POOL_SIZE is not set

### We never want Zephyr's copy of tinycrypt.  If tinycrypt is needed,
### MCUboot has its own copy in tree.


CONFIG_FPROTECT=n
CONFIG_BOOT_WATCHDOG_FEED=n

# Use PSA/CRACEN-backed ECDSA verification on nRF54L instead of TinyCrypt.
#CONFIG_NRF_SECURITY=y
#CONFIG_BOOT_ECDSA_PSA=y

### Various Zephyr boards enable features that we don't want.
# CONFIG_BT is not set
# CONFIG_I2C is not set

#CONFIG_LOG=n
# NCS boot banner
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
#inprove the swap speed
CONFIG_NRF_RRAM_WRITE_BUFFER_SIZE=32




#时钟相关配置
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=n      #使用内部rc振荡器 LFRC
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y    #使用外部低功耗32.768khz晶振
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION=n  #启用校准
# 校准周期（以毫秒秒为单位）
# CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_PERIOD=256000
# 校准温度变化阈值（单位摄氏度，默认2°C）
# CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_TEMP_DIFF=2
